### ISSUE TITLE
Languages are now modules

### ISSUE THREAD

**Issue by ivanistheone** [bramstein/hypher#11]
but jquery.hyper.js does not know how to load them.

```
Uncaught ReferenceError: module is not defined en-us.js:3
(anonymous function)
```

in en-us.js

**Comment by normanlolx** [comment]
Hummm, I just `$ npm install hypher hyphenation.de` which gave me:

```bash
+ hypher@0.2.5
+ hyphenation.de@0.2.1
```

Then I included the following scripts in my HTML head:

* node_modules/hypher/dist/jquery.hypher.js
* node_modules/hyphenation.de/lib/de.js

And then I get the above error. I don't see any `dist/browser` directory. How do I fix that error then?

**Comment by normanlolx** [comment]
Ooookay, so I had to include [`bramstein/hyphenation-patterns`](https://github.com/bramstein/hyphenation-patterns) instead of `hyphenation.de`.

    $ npm install hypher git+https://git@github.com:fluid-project/hyphenation-patterns.git

And then include:

* node_modules/hypher/dist/jquery.hypher.js
* node_modules/@fluid-project/hyphenation-patterns/dist/browser/de.js
