### ISSUE TITLE
zero-width space breaks inline HTML

### ISSUE THREAD

**Issue by harmenjanssen** [bramstein/hypher#20]
Given the HTML `<p>Lorem ipsum <b>Dolor</b> sit amet.</p>`, a zero-width space is inserted right before the slash of the closing `</b>`. 

This breaks the HTML when inserting in the DOM. I'm using the Dutch language pack, so the problem can be reproduced with:

```
document.querySelector('.my-element').innerHTML = window.Hypher.languages.nl.hyphenateText('<p>Lorem ipsum <b>Dolor</b> sit amet.</p>');
```

You'll see the closing `</b>` gets mangled (Chrome DevTools shows the tag in an HTML comment) and the remainder of the paragraph is bold.

I "fixed" it by commenting the following line of the `hyphenateText` function:

```words[i] += '\u200B';```

Obviously that's no long-term solution, but I'm unclear what the zero-width spaces are used for, so I'm hoping you can shed some light on this so we can come up with a proper fix.

**Comment by bramstein** [comment]
Hi,

The hyphenateText method does not support inline HTML elements. Supporting this would require implementing a DOM parser, which I prefer not to do :)

Instead you can use the browser's DOM to do the same. Once you've selected the elements you want to hyphenate you can do a tree traversal and apply `hyphenateText` to all text nodes. You can see an example of this in the jQuery plugin: https://github.com/bramstein/hypher/blob/master/lib/jquery.hypher.js

I hope that helps.

**Comment by harmenjanssen** [comment]
Ah, that helps a lot, actually :)
Thanks, I'll close this one and look at the jQuery implementation for a solution.

**Comment by Southgarden116** [comment]
What is the purpose of this zero-width space though?

**Comment by Southgarden116** [comment]
What is the purpose of this zero-width space though? It would be nice if I could decide if I want this to happen or not.
