### ISSUE TITLE
jquery.hypher.js not in dist folder in npm package

### ISSUE THREAD

**Issue by andrechrist** [bramstein/hypher#21]
Hi,

when I install the hypher package via npm install hypher, then the jquery files are not included. We are organizing our sources this way also in our web projects so I wonder if there is any better way to get the jquery file?

Thanks,
André

**Comment by bramstein** [comment]
Hi André,

That's an excellent idea. I've changed it so that the dist directory is also available when you install through npm.

Thanks,

Bram
