### ISSUE TITLE
Handling of soft hyphen is inconsistent.

### ISSUE THREAD

**Issue by unageanu** [bramstein/hypher#34]
`Hyper#hyphenate()` is not hyphenate a string that contains a soft hyphen character. 
But `Hyper#hyphenateText()` is not.

```javascript
var hypher = new Hypher(dictionary);
hypher.hyphenate('hyp\u00ADhenate');  // => ['hy\u00ADphenate']
hypher.hyphenateText('hyp\u00ADhenate').split('\u00AD');  // => ["hyp", "hen", "ate"]
```

I think it is better to handle it consisitently.

**Comment by bramstein** [comment]
Thanks! I'll merge in your pull request and release a new version.

**Comment by unageanu** [comment]
Thanks for merging my pull request!
