### ISSUE TITLE
Compatible with Tiurin's patterns. 

### ISSUE THREAD

**Issue by gusbemacbe** [bramstein/hypher#39]
Hello @bramstein!

Good morning,

I would like to know if your project is compatible with Eugene Tiurin's patterns because the hyphenation projects do not have Georgian hyphenation pattern. 

Check: https://github.com/ytiurin/hyphen/tree/master/patterns

**Comment by bramstein** [comment]
I just had a quick look, but it doesn't seem compatible. Shouldn't be too hard to convert though.

**Comment by gusbemacbe** [comment]
I duplicated the English pattern project and copied the part of hyphenation pattern and pasted on the file, and nothing worked. I do not know how to build a Georgian hyphenation. I tried to understand this body full of alphanumerics. Will you try?

**Comment by shoshia** [comment]
ok..I converted patterns using this page
http://mnater.github.io/Hyphenator/compressor.html

please check http://tex.tsu.ge/files/patterns/
there is a file ka_new_format.js rename it to ka.js
and try it :) ...
I dont have time right now....
will check later

**Comment by gusbemacbe** [comment]
@bramstein, @shoshia is the author of this Georgian pattern, he tested and it worked. 

[test.html from shoshia](https://github.com/bramstein/hypher/files/1198155/test.html.zip)
