### ISSUE TITLE
Exceptions don't work (using jQuery)

### ISSUE THREAD

**Issue by melanie-go** [bramstein/hypher#41]
Hello,

I have trouble to get exceptions words to work. I'm using the jQuery versions with this type of language file : 
```
{
'id': 'de',
'leftmin': 2,
'rightmin': 2,
'exceptions': "word1, word2"
'patterns': { }
}
```
The script adds `&shy; `in the exceptions words, I don't want hyphenation at all on theses words.
Does my code right ? Can you help me with this ? 

Thanks,
Regards

**Comment by mawiswiss** [comment]
I think I also had issues with that a couple of years back.

I created a jQuery version of Hypher years back and exceptions work there:
https://github.com/marcwieland95/hypher-for-jQuery

Cheers
Marc

**Comment by melanie-go** [comment]
Thank you. I have implemented your jQuery version but I still have some issues. 
I let you know in the plugin page.

Cheers
Melanie
