### ISSUE TITLE
Example of jQuery with parameters

### ISSUE THREAD

**Issue by bramvandenbulcke** [bramstein/hypher#43]
I'm using Hypher with jQuery. We need hyphenation for Edge on Windows.  

This is the code I'm using: 

`$('html[lang="nl"] .l-hero .title h2').hyphenate('nl');`

This is working fine but it also hyphenates short words and it can show a small part of a word on another line. 

I would like to use the **minLength** (for example words longer than 8 characters), **leftmin** (I would pick 4 characters) and **rightmin** (also 4 characters) parameters but I'm unable to implement the code. Can someone provide me an example? Do these parameters work with jQuery?

**Comment by mawiswiss** [comment]
Hey hey

The options object (second argument) isn't passed in the jQuery version. As far as I remember there's no way to do that.
But many many years ago I created an improved jQuery version for Hypher. Maybe check that out.
https://github.com/marcwieland95/hypher-for-jQuery

**Comment by bramvandenbulcke** [comment]
Thanks for the input! 

I will try that.
